# Generated by Django 4.0 on 2022-02-15 10:50

import datetime
from django.db import migrations, models
import django.db.models.deletion
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_category_upload_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_product',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('address', models.CharField(blank=sqlalchemy.sql.expression.true, default='', max_length=50)),
                ('phone', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.register')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.upload_product')),
            ],
        ),
    ]
