# Generated by Django 4.0 on 2022-02-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_order_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='registeration',
        ),
    ]
