# Generated by Django 4.0 on 2022-02-28 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_demo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='demo',
            new_name='demodb',
        ),
    ]
